services:
  - type: web
    name: CYBER-PANDA-MD-V.10
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
